/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDialerRouteImport } from './routes/_authenticated/dialer'
import { Route as ApiPublicTwilioVoiceRouteImport } from './routes/api/public/twilio-voice'
import { Route as ApiPublicTwilioStatusRouteImport } from './routes/api/public/twilio-status'
import { Route as ApiPublicTwilioInboundRouteImport } from './routes/api/public/twilio-inbound'
import { Route as ApiPublicInboundRouteRouteImport } from './routes/api/public/inbound-route'
import { Route as ApiPublicAsteriskEventsRouteImport } from './routes/api/public/asterisk-events'
import { Route as AuthenticatedAdminOutboundRouteImport } from './routes/_authenticated/admin/outbound'
import { Route as AuthenticatedAdminLiveRouteImport } from './routes/_authenticated/admin/live'
import { Route as AuthenticatedAdminInboundRouteImport } from './routes/_authenticated/admin/inbound'
import { Route as AuthenticatedAdminFieldsRouteImport } from './routes/_authenticated/admin/fields'
import { Route as AuthenticatedAdminContactsRouteImport } from './routes/_authenticated/admin/contacts'
import { Route as AuthenticatedAdminCallsRouteImport } from './routes/_authenticated/admin/calls'
import { Route as AuthenticatedAdminAgentsRouteImport } from './routes/_authenticated/admin/agents'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDialerRoute = AuthenticatedDialerRouteImport.update({
  id: '/dialer',
  path: '/dialer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicTwilioVoiceRoute = ApiPublicTwilioVoiceRouteImport.update({
  id: '/api/public/twilio-voice',
  path: '/api/public/twilio-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioStatusRoute = ApiPublicTwilioStatusRouteImport.update({
  id: '/api/public/twilio-status',
  path: '/api/public/twilio-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioInboundRoute = ApiPublicTwilioInboundRouteImport.update({
  id: '/api/public/twilio-inbound',
  path: '/api/public/twilio-inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInboundRouteRoute = ApiPublicInboundRouteRouteImport.update({
  id: '/api/public/inbound-route',
  path: '/api/public/inbound-route',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsteriskEventsRoute = ApiPublicAsteriskEventsRouteImport.update({
  id: '/api/public/asterisk-events',
  path: '/api/public/asterisk-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminOutboundRoute =
  AuthenticatedAdminOutboundRouteImport.update({
    id: '/admin/outbound',
    path: '/admin/outbound',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLiveRoute = AuthenticatedAdminLiveRouteImport.update({
  id: '/admin/live',
  path: '/admin/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminInboundRoute =
  AuthenticatedAdminInboundRouteImport.update({
    id: '/admin/inbound',
    path: '/admin/inbound',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFieldsRoute =
  AuthenticatedAdminFieldsRouteImport.update({
    id: '/admin/fields',
    path: '/admin/fields',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminContactsRoute =
  AuthenticatedAdminContactsRouteImport.update({
    id: '/admin/contacts',
    path: '/admin/contacts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCallsRoute = AuthenticatedAdminCallsRouteImport.update({
  id: '/admin/calls',
  path: '/admin/calls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAgentsRoute =
  AuthenticatedAdminAgentsRouteImport.update({
    id: '/admin/agents',
    path: '/admin/agents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dialer': typeof AuthenticatedDialerRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/calls': typeof AuthenticatedAdminCallsRoute
  '/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/admin/fields': typeof AuthenticatedAdminFieldsRoute
  '/admin/inbound': typeof AuthenticatedAdminInboundRoute
  '/admin/live': typeof AuthenticatedAdminLiveRoute
  '/admin/outbound': typeof AuthenticatedAdminOutboundRoute
  '/api/public/asterisk-events': typeof ApiPublicAsteriskEventsRoute
  '/api/public/inbound-route': typeof ApiPublicInboundRouteRoute
  '/api/public/twilio-inbound': typeof ApiPublicTwilioInboundRoute
  '/api/public/twilio-status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio-voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dialer': typeof AuthenticatedDialerRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/calls': typeof AuthenticatedAdminCallsRoute
  '/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/admin/fields': typeof AuthenticatedAdminFieldsRoute
  '/admin/inbound': typeof AuthenticatedAdminInboundRoute
  '/admin/live': typeof AuthenticatedAdminLiveRoute
  '/admin/outbound': typeof AuthenticatedAdminOutboundRoute
  '/api/public/asterisk-events': typeof ApiPublicAsteriskEventsRoute
  '/api/public/inbound-route': typeof ApiPublicInboundRouteRoute
  '/api/public/twilio-inbound': typeof ApiPublicTwilioInboundRoute
  '/api/public/twilio-status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio-voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dialer': typeof AuthenticatedDialerRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/_authenticated/admin/calls': typeof AuthenticatedAdminCallsRoute
  '/_authenticated/admin/contacts': typeof AuthenticatedAdminContactsRoute
  '/_authenticated/admin/fields': typeof AuthenticatedAdminFieldsRoute
  '/_authenticated/admin/inbound': typeof AuthenticatedAdminInboundRoute
  '/_authenticated/admin/live': typeof AuthenticatedAdminLiveRoute
  '/_authenticated/admin/outbound': typeof AuthenticatedAdminOutboundRoute
  '/api/public/asterisk-events': typeof ApiPublicAsteriskEventsRoute
  '/api/public/inbound-route': typeof ApiPublicInboundRouteRoute
  '/api/public/twilio-inbound': typeof ApiPublicTwilioInboundRoute
  '/api/public/twilio-status': typeof ApiPublicTwilioStatusRoute
  '/api/public/twilio-voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dialer'
    | '/history'
    | '/admin/agents'
    | '/admin/calls'
    | '/admin/contacts'
    | '/admin/fields'
    | '/admin/inbound'
    | '/admin/live'
    | '/admin/outbound'
    | '/api/public/asterisk-events'
    | '/api/public/inbound-route'
    | '/api/public/twilio-inbound'
    | '/api/public/twilio-status'
    | '/api/public/twilio-voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dialer'
    | '/history'
    | '/admin/agents'
    | '/admin/calls'
    | '/admin/contacts'
    | '/admin/fields'
    | '/admin/inbound'
    | '/admin/live'
    | '/admin/outbound'
    | '/api/public/asterisk-events'
    | '/api/public/inbound-route'
    | '/api/public/twilio-inbound'
    | '/api/public/twilio-status'
    | '/api/public/twilio-voice'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dialer'
    | '/_authenticated/history'
    | '/_authenticated/admin/agents'
    | '/_authenticated/admin/calls'
    | '/_authenticated/admin/contacts'
    | '/_authenticated/admin/fields'
    | '/_authenticated/admin/inbound'
    | '/_authenticated/admin/live'
    | '/_authenticated/admin/outbound'
    | '/api/public/asterisk-events'
    | '/api/public/inbound-route'
    | '/api/public/twilio-inbound'
    | '/api/public/twilio-status'
    | '/api/public/twilio-voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicAsteriskEventsRoute: typeof ApiPublicAsteriskEventsRoute
  ApiPublicInboundRouteRoute: typeof ApiPublicInboundRouteRoute
  ApiPublicTwilioInboundRoute: typeof ApiPublicTwilioInboundRoute
  ApiPublicTwilioStatusRoute: typeof ApiPublicTwilioStatusRoute
  ApiPublicTwilioVoiceRoute: typeof ApiPublicTwilioVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dialer': {
      id: '/_authenticated/dialer'
      path: '/dialer'
      fullPath: '/dialer'
      preLoaderRoute: typeof AuthenticatedDialerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/twilio-voice': {
      id: '/api/public/twilio-voice'
      path: '/api/public/twilio-voice'
      fullPath: '/api/public/twilio-voice'
      preLoaderRoute: typeof ApiPublicTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio-status': {
      id: '/api/public/twilio-status'
      path: '/api/public/twilio-status'
      fullPath: '/api/public/twilio-status'
      preLoaderRoute: typeof ApiPublicTwilioStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio-inbound': {
      id: '/api/public/twilio-inbound'
      path: '/api/public/twilio-inbound'
      fullPath: '/api/public/twilio-inbound'
      preLoaderRoute: typeof ApiPublicTwilioInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inbound-route': {
      id: '/api/public/inbound-route'
      path: '/api/public/inbound-route'
      fullPath: '/api/public/inbound-route'
      preLoaderRoute: typeof ApiPublicInboundRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asterisk-events': {
      id: '/api/public/asterisk-events'
      path: '/api/public/asterisk-events'
      fullPath: '/api/public/asterisk-events'
      preLoaderRoute: typeof ApiPublicAsteriskEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/outbound': {
      id: '/_authenticated/admin/outbound'
      path: '/admin/outbound'
      fullPath: '/admin/outbound'
      preLoaderRoute: typeof AuthenticatedAdminOutboundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/live': {
      id: '/_authenticated/admin/live'
      path: '/admin/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AuthenticatedAdminLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/inbound': {
      id: '/_authenticated/admin/inbound'
      path: '/admin/inbound'
      fullPath: '/admin/inbound'
      preLoaderRoute: typeof AuthenticatedAdminInboundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/fields': {
      id: '/_authenticated/admin/fields'
      path: '/admin/fields'
      fullPath: '/admin/fields'
      preLoaderRoute: typeof AuthenticatedAdminFieldsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/contacts': {
      id: '/_authenticated/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AuthenticatedAdminContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/calls': {
      id: '/_authenticated/admin/calls'
      path: '/admin/calls'
      fullPath: '/admin/calls'
      preLoaderRoute: typeof AuthenticatedAdminCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/agents': {
      id: '/_authenticated/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AuthenticatedAdminAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDialerRoute: typeof AuthenticatedDialerRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedAdminAgentsRoute: typeof AuthenticatedAdminAgentsRoute
  AuthenticatedAdminCallsRoute: typeof AuthenticatedAdminCallsRoute
  AuthenticatedAdminContactsRoute: typeof AuthenticatedAdminContactsRoute
  AuthenticatedAdminFieldsRoute: typeof AuthenticatedAdminFieldsRoute
  AuthenticatedAdminInboundRoute: typeof AuthenticatedAdminInboundRoute
  AuthenticatedAdminLiveRoute: typeof AuthenticatedAdminLiveRoute
  AuthenticatedAdminOutboundRoute: typeof AuthenticatedAdminOutboundRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDialerRoute: AuthenticatedDialerRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedAdminAgentsRoute: AuthenticatedAdminAgentsRoute,
  AuthenticatedAdminCallsRoute: AuthenticatedAdminCallsRoute,
  AuthenticatedAdminContactsRoute: AuthenticatedAdminContactsRoute,
  AuthenticatedAdminFieldsRoute: AuthenticatedAdminFieldsRoute,
  AuthenticatedAdminInboundRoute: AuthenticatedAdminInboundRoute,
  AuthenticatedAdminLiveRoute: AuthenticatedAdminLiveRoute,
  AuthenticatedAdminOutboundRoute: AuthenticatedAdminOutboundRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicAsteriskEventsRoute: ApiPublicAsteriskEventsRoute,
  ApiPublicInboundRouteRoute: ApiPublicInboundRouteRoute,
  ApiPublicTwilioInboundRoute: ApiPublicTwilioInboundRoute,
  ApiPublicTwilioStatusRoute: ApiPublicTwilioStatusRoute,
  ApiPublicTwilioVoiceRoute: ApiPublicTwilioVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
